package me.godap.ins;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LOGGED_USER".
 */
@Entity
public class LoggedUser {

    @Id
    private Long userId;
    private String userName;
    private String fullName;
    private String avatarUrl;

    @Generated(hash = 331065833)
    public LoggedUser() {
    }

    public LoggedUser(Long userId) {
        this.userId = userId;
    }

    @Generated(hash = 495344771)
    public LoggedUser(Long userId, String userName, String fullName, String avatarUrl) {
        this.userId = userId;
        this.userName = userName;
        this.fullName = fullName;
        this.avatarUrl = avatarUrl;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

}
