package me.godap.ins;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "USER_DETAIL".
 */
@Entity
public class UserDetail {

    @Id
    private Long userId;
    private String userName;
    private String fullName;
    private String externalUrl;
    private Boolean isFavorite;
    private String publicPhoneCountryCode;
    private String publicPhone;
    private String publicEmail;
    private Integer geoMediaCount;
    private Integer userTagsCount;
    private String avatarUrl;
    private String addressStreet;
    private String cityName;
    private Integer followerCount;
    private Integer followingCount;

    @Generated(hash = 1767819458)
    public UserDetail() {
    }

    public UserDetail(Long userId) {
        this.userId = userId;
    }

    @Generated(hash = 843359794)
    public UserDetail(Long userId, String userName, String fullName, String externalUrl, Boolean isFavorite, String publicPhoneCountryCode, String publicPhone, String publicEmail, Integer geoMediaCount, Integer userTagsCount, String avatarUrl, String addressStreet, String cityName, Integer followerCount, Integer followingCount) {
        this.userId = userId;
        this.userName = userName;
        this.fullName = fullName;
        this.externalUrl = externalUrl;
        this.isFavorite = isFavorite;
        this.publicPhoneCountryCode = publicPhoneCountryCode;
        this.publicPhone = publicPhone;
        this.publicEmail = publicEmail;
        this.geoMediaCount = geoMediaCount;
        this.userTagsCount = userTagsCount;
        this.avatarUrl = avatarUrl;
        this.addressStreet = addressStreet;
        this.cityName = cityName;
        this.followerCount = followerCount;
        this.followingCount = followingCount;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getExternalUrl() {
        return externalUrl;
    }

    public void setExternalUrl(String externalUrl) {
        this.externalUrl = externalUrl;
    }

    public Boolean getIsFavorite() {
        return isFavorite;
    }

    public void setIsFavorite(Boolean isFavorite) {
        this.isFavorite = isFavorite;
    }

    public String getPublicPhoneCountryCode() {
        return publicPhoneCountryCode;
    }

    public void setPublicPhoneCountryCode(String publicPhoneCountryCode) {
        this.publicPhoneCountryCode = publicPhoneCountryCode;
    }

    public String getPublicPhone() {
        return publicPhone;
    }

    public void setPublicPhone(String publicPhone) {
        this.publicPhone = publicPhone;
    }

    public String getPublicEmail() {
        return publicEmail;
    }

    public void setPublicEmail(String publicEmail) {
        this.publicEmail = publicEmail;
    }

    public Integer getGeoMediaCount() {
        return geoMediaCount;
    }

    public void setGeoMediaCount(Integer geoMediaCount) {
        this.geoMediaCount = geoMediaCount;
    }

    public Integer getUserTagsCount() {
        return userTagsCount;
    }

    public void setUserTagsCount(Integer userTagsCount) {
        this.userTagsCount = userTagsCount;
    }

    public String getAvatarUrl() {
        return avatarUrl;
    }

    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl;
    }

    public String getAddressStreet() {
        return addressStreet;
    }

    public void setAddressStreet(String addressStreet) {
        this.addressStreet = addressStreet;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public Integer getFollowerCount() {
        return followerCount;
    }

    public void setFollowerCount(Integer followerCount) {
        this.followerCount = followerCount;
    }

    public Integer getFollowingCount() {
        return followingCount;
    }

    public void setFollowingCount(Integer followingCount) {
        this.followingCount = followingCount;
    }

}
